from enum import Enum
class ClaimStatus(Enum):
    SUBITTED = "SUBMITTED"
    EXCEEDS_UPLOAD_LIMIT = "EXCEEDS_UPLOAD_LIMIT"
    VERIFYING_DOCUMENTS = "VERIFYING_DOCUMENTS"
    PERFORMING_OCR = "PERFORMING_OCR"
    EXTRACTING_DATA_FROM_DOCUMENTS = "EXTRACTING_DATA_FROM_DOCUMENTS"
    DOCUMENT_VERIFICATION_FAILED = "DOCUMENT_VERIFICATION_FAILED"
    VALIDATING_POLICY = "VALIDATING_POLICY"
    ANALYZING_FRAUD = "ANALYZING_FRAUD"
    DECISION_GENERATION = "DECISION_GENERATION"
    COMPLETED = "COMPLETED"
    FAILURE = "FAILURE"

